-- SuntCastigator — schema v1
-- Applied via Supabase Dashboard SQL Editor on a fresh project, or via `supabase db push`.
-- Everything is idempotent-friendly for the initial run only; do NOT edit this file
-- after it has been applied to any environment — add a new 0002_*.sql instead.

-- ============================================================================
-- Extensions
-- ============================================================================

create extension if not exists pgcrypto;      -- gen_random_uuid()
create extension if not exists citext;        -- reserved for future case-insensitive email

-- ============================================================================
-- Tables
-- ============================================================================

create table brands (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  slug       text not null unique,
  logo_url   text,
  created_at timestamptz not null default now()
);

create table brand_users (
  brand_id   uuid not null references brands(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  role       text not null check (role in ('owner','editor')),
  created_at timestamptz not null default now(),
  primary key (brand_id, user_id)
);

create table products (
  id       uuid primary key default gen_random_uuid(),
  brand_id uuid not null references brands(id) on delete cascade,
  sku      text not null,
  name     text not null,
  unique (brand_id, sku)
);
create index ix_products_brand on products(brand_id);

create table campaigns (
  id                     uuid primary key default gen_random_uuid(),
  brand_id               uuid not null references brands(id) on delete cascade,
  name                   text not null,
  slug                   text not null unique,
  status                 text not null default 'draft' check (status in ('draft','active','ended')),
  starts_at              date,
  ends_at                date,
  code_length            int check (code_length between 6 and 14),
  code_charset           text check (code_charset in ('letters','digits','alphanumeric')),
  code_regex             text,
  single_use_codes       boolean not null default true,
  block_invalid_format   boolean not null default true,
  limit_per_contact_24h  int,
  rules_pdf_path         text,
  hero_image_url         text,
  how_to_text            text,
  created_by             uuid references auth.users(id),
  created_at             timestamptz not null default now(),
  check (starts_at is null or ends_at is null or starts_at <= ends_at)
);
create index ix_campaigns_brand on campaigns(brand_id);
create index ix_campaigns_status on campaigns(status) where status = 'active';

create table campaign_products (
  campaign_id uuid not null references campaigns(id) on delete cascade,
  product_id  uuid not null references products(id)  on delete cascade,
  primary key (campaign_id, product_id)
);
create index ix_campaign_products_product on campaign_products(product_id);

create table prize_tiers (
  id          uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references campaigns(id) on delete cascade,
  name        text not null,
  quantity    int check (quantity is null or quantity > 0),
  value_lei   numeric(10,2) not null check (value_lei >= 0),
  kind        text not null check (kind in ('instant','draw')),
  taxable     boolean not null default false,
  sort_order  int not null default 0
);
create index ix_prize_tiers_campaign on prize_tiers(campaign_id);

create table code_entries (
  id              uuid primary key default gen_random_uuid(),
  campaign_id     uuid not null references campaigns(id) on delete cascade,
  code            text not null,
  full_name       text not null,
  contact         text not null,
  ip              inet,
  status          text not null check (status in ('valid','duplicate','invalid')),
  gdpr_consent_at timestamptz not null,
  created_at      timestamptz not null default now()
);
-- Prevents two 'valid' rows with the same code inside a campaign; 'duplicate'
-- and 'invalid' rows are audit trail and are allowed to coexist.
create unique index uq_code_entries_valid on code_entries(campaign_id, code) where status = 'valid';
create index ix_code_entries_ip           on code_entries(campaign_id, ip, created_at);
create index ix_code_entries_contact      on code_entries(campaign_id, contact, created_at);
create index ix_code_entries_campaign_time on code_entries(campaign_id, created_at);

create table draws (
  id                uuid primary key default gen_random_uuid(),
  campaign_id       uuid not null references campaigns(id),
  prize_tier_id     uuid not null references prize_tiers(id),
  seed              text not null,
  participant_count int  not null check (participant_count >= 0),
  participants_hash text not null,
  ran_by            uuid not null references auth.users(id),
  ran_at            timestamptz not null default now()
);
create index ix_draws_campaign on draws(campaign_id);

create table winners (
  draw_id  uuid not null references draws(id) on delete cascade,
  entry_id uuid not null references code_entries(id),
  position int  not null check (position > 0),
  primary key (draw_id, position),
  unique (draw_id, entry_id)
);

create table settings (
  key   text primary key,
  value jsonb not null
);

-- ============================================================================
-- Helpers
-- ============================================================================

-- is_brand_member(b) — true iff the current auth.uid() is a member of brand b.
-- SECURITY DEFINER so RLS policies calling it don't recurse into brand_users
-- RLS (which itself uses this function).
create or replace function public.is_brand_member(b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from brand_users bu
    where bu.brand_id = b
      and bu.user_id  = auth.uid()
  );
$$;
revoke execute on function public.is_brand_member(uuid) from public;
grant  execute on function public.is_brand_member(uuid) to authenticated;

-- ============================================================================
-- submit_entry() — the ONLY path for public entry submission.
-- Called from POST /api/entries via the service-role client. Atomic checks:
--   1. campaign exists, status=active, within [starts_at, ends_at] window
--   2. per-IP rate limit (settings.entry_rate_limit_per_ip_hour)
--   3. per-contact rate limit (campaigns.limit_per_contact_24h, if set)
--   4. format regex (campaigns.code_regex) — if fails and block_invalid_format,
--      records status='invalid' and returns
--   5. duplicate check (only when single_use_codes) — records 'duplicate'
--   6. otherwise inserts 'valid'
-- Rate-limit and window failures RAISE so the caller returns 429/400.
-- Format/duplicate failures INSERT an audit row and return the status.
-- ============================================================================

create or replace function public.submit_entry(
  p_campaign_id     uuid,
  p_code            text,
  p_full_name       text,
  p_contact         text,
  p_ip              inet,
  p_gdpr_consent_at timestamptz
)
returns table (entry_id uuid, entry_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign      campaigns%rowtype;
  v_ip_limit      int;
  v_ip_count      int;
  v_contact_count int;
  v_duplicate     boolean;
  v_new_id        uuid;
begin
  if p_code is null or p_full_name is null or p_contact is null or p_gdpr_consent_at is null then
    raise exception 'missing_field' using errcode = '22004';
  end if;

  select * into v_campaign from campaigns where id = p_campaign_id;
  if not found then
    raise exception 'campaign_not_found' using errcode = 'P0002';
  end if;

  if v_campaign.status <> 'active' then
    raise exception 'campaign_not_active' using errcode = 'P0001';
  end if;
  if v_campaign.starts_at is not null and current_date < v_campaign.starts_at then
    raise exception 'campaign_not_started' using errcode = 'P0001';
  end if;
  if v_campaign.ends_at is not null and current_date > v_campaign.ends_at then
    raise exception 'campaign_ended' using errcode = 'P0001';
  end if;

  select coalesce((value->>'limit')::int, 20)
    into v_ip_limit
    from settings
    where key = 'entry_rate_limit_per_ip_hour';

  if p_ip is not null and v_ip_limit is not null and v_ip_limit > 0 then
    select count(*) into v_ip_count
      from code_entries
      where campaign_id = p_campaign_id
        and ip          = p_ip
        and created_at  > now() - interval '1 hour';
    if v_ip_count >= v_ip_limit then
      raise exception 'rate_limit_ip' using errcode = 'P0001';
    end if;
  end if;

  if v_campaign.limit_per_contact_24h is not null and v_campaign.limit_per_contact_24h > 0 then
    select count(*) into v_contact_count
      from code_entries
      where campaign_id = p_campaign_id
        and contact     = p_contact
        and created_at  > now() - interval '24 hours';
    if v_contact_count >= v_campaign.limit_per_contact_24h then
      raise exception 'rate_limit_contact' using errcode = 'P0001';
    end if;
  end if;

  if v_campaign.code_regex is not null
     and v_campaign.code_regex <> ''
     and p_code !~ v_campaign.code_regex
  then
    if v_campaign.block_invalid_format then
      insert into code_entries(campaign_id, code, full_name, contact, ip, status, gdpr_consent_at)
      values (p_campaign_id, p_code, p_full_name, p_contact, p_ip, 'invalid', p_gdpr_consent_at)
      returning id into v_new_id;
      return query select v_new_id, 'invalid'::text;
      return;
    end if;
  end if;

  if v_campaign.single_use_codes then
    select exists (
      select 1 from code_entries
      where campaign_id = p_campaign_id
        and code        = p_code
        and status      = 'valid'
    ) into v_duplicate;
    if v_duplicate then
      insert into code_entries(campaign_id, code, full_name, contact, ip, status, gdpr_consent_at)
      values (p_campaign_id, p_code, p_full_name, p_contact, p_ip, 'duplicate', p_gdpr_consent_at)
      returning id into v_new_id;
      return query select v_new_id, 'duplicate'::text;
      return;
    end if;
  end if;

  insert into code_entries(campaign_id, code, full_name, contact, ip, status, gdpr_consent_at)
  values (p_campaign_id, p_code, p_full_name, p_contact, p_ip, 'valid', p_gdpr_consent_at)
  returning id into v_new_id;
  return query select v_new_id, 'valid'::text;
end;
$$;

revoke execute on function public.submit_entry(uuid, text, text, text, inet, timestamptz) from public;
grant  execute on function public.submit_entry(uuid, text, text, text, inet, timestamptz) to service_role;

-- ============================================================================
-- Row Level Security — ON everywhere, deny by default.
-- Service-role bypasses RLS (used by /api/entries and CSV export).
-- Anon has ZERO access to any table; consumer entry goes through submit_entry.
-- ============================================================================

alter table brands            enable row level security;
alter table brand_users       enable row level security;
alter table products          enable row level security;
alter table campaigns         enable row level security;
alter table campaign_products enable row level security;
alter table prize_tiers       enable row level security;
alter table code_entries      enable row level security;
alter table draws             enable row level security;
alter table winners           enable row level security;
alter table settings          enable row level security;

-- brands: members see and update; no self-insert (operator seeds).
create policy brands_select on brands
  for select to authenticated
  using (is_brand_member(id));

create policy brands_update on brands
  for update to authenticated
  using (is_brand_member(id))
  with check (is_brand_member(id));

-- brand_users: a member sees the membership list of their own brand.
create policy brand_users_select on brand_users
  for select to authenticated
  using (is_brand_member(brand_id));

-- products: full CRUD for members of the owning brand.
create policy products_select on products
  for select to authenticated
  using (is_brand_member(brand_id));

create policy products_insert on products
  for insert to authenticated
  with check (is_brand_member(brand_id));

create policy products_update on products
  for update to authenticated
  using (is_brand_member(brand_id))
  with check (is_brand_member(brand_id));

create policy products_delete on products
  for delete to authenticated
  using (is_brand_member(brand_id));

-- campaigns: full CRUD for members.
create policy campaigns_select on campaigns
  for select to authenticated
  using (is_brand_member(brand_id));

create policy campaigns_insert on campaigns
  for insert to authenticated
  with check (is_brand_member(brand_id));

create policy campaigns_update on campaigns
  for update to authenticated
  using (is_brand_member(brand_id))
  with check (is_brand_member(brand_id));

create policy campaigns_delete on campaigns
  for delete to authenticated
  using (is_brand_member(brand_id));

-- campaign_products: membership derived from campaign.
create policy campaign_products_select on campaign_products
  for select to authenticated
  using (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

create policy campaign_products_insert on campaign_products
  for insert to authenticated
  with check (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

create policy campaign_products_delete on campaign_products
  for delete to authenticated
  using (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

-- prize_tiers: full CRUD for members of the owning brand (via campaign).
create policy prize_tiers_select on prize_tiers
  for select to authenticated
  using (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

create policy prize_tiers_insert on prize_tiers
  for insert to authenticated
  with check (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

create policy prize_tiers_update on prize_tiers
  for update to authenticated
  using (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)))
  with check (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

create policy prize_tiers_delete on prize_tiers
  for delete to authenticated
  using (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

-- code_entries: members SELECT their brand's entries; no direct INSERT/UPDATE/DELETE
-- (writes go exclusively through submit_entry, service-role only).
create policy code_entries_select on code_entries
  for select to authenticated
  using (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

-- draws: members SELECT; INSERT is done server-side via service-role from the draw route.
create policy draws_select on draws
  for select to authenticated
  using (exists (select 1 from campaigns c where c.id = campaign_id and is_brand_member(c.brand_id)));

-- winners: members SELECT via parent draw's campaign.
create policy winners_select on winners
  for select to authenticated
  using (exists (
    select 1
    from draws d
    join campaigns c on c.id = d.campaign_id
    where d.id = draw_id
      and is_brand_member(c.brand_id)
  ));

-- settings: no policies. Only service_role reads/writes; that's the point.
-- (RLS is enabled and there are zero policies, so authenticated & anon get nothing.)
