-- SuntCastigator — schema v2: draw engine support
-- Apply via Supabase Dashboard SQL Editor (same as 0001_init.sql), or
-- `supabase db push` once the project is linked. Do NOT edit this file
-- after it has been applied to any environment — add 0003_*.sql instead.

-- ============================================================================
-- Guard: a prize tier can only be drawn once. Backs the app-level
-- already-drawn check inside record_draw() below with a hard constraint,
-- so two concurrent draw requests for the same tier can't both succeed.
-- ============================================================================

alter table draws
  add constraint uq_draws_campaign_tier unique (campaign_id, prize_tier_id);

-- ============================================================================
-- record_draw() — the ONLY path for persisting a draw's result.
-- Called from POST /api/campaigns/[id]/draw (lib/draw/engine.ts) via the
-- service-role client, after the seed, participants hash, and winner
-- ordering have already been computed in pure JS (see lib/draw/engine.ts —
-- the same algorithm can be re-run standalone from the stored seed and
-- snapshot to reproduce the winners, which is the whole point: auditable,
-- disputable draws).
-- Inserts into `draws` and `winners` inside one function call, which
-- Postgres runs as a single implicit transaction — if either insert fails,
-- both roll back. Re-checks "already drawn" here too (not just app-side)
-- as the race-safe half of the guarantee; uq_draws_campaign_tier above is
-- the hard backstop if two requests land at the same instant.
-- ============================================================================

create or replace function public.record_draw(
  p_campaign_id       uuid,
  p_prize_tier_id     uuid,
  p_seed              text,
  p_participant_count int,
  p_participants_hash text,
  p_ran_by            uuid,
  p_winner_entry_ids  uuid[]
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_draw_id uuid;
begin
  if exists (
    select 1 from draws
    where campaign_id = p_campaign_id and prize_tier_id = p_prize_tier_id
  ) then
    raise exception 'already_drawn' using errcode = 'P0001';
  end if;

  insert into draws (campaign_id, prize_tier_id, seed, participant_count, participants_hash, ran_by)
  values (p_campaign_id, p_prize_tier_id, p_seed, p_participant_count, p_participants_hash, p_ran_by)
  returning id into v_draw_id;

  insert into winners (draw_id, entry_id, position)
  select v_draw_id, entry_id, ordinality::int
  from unnest(p_winner_entry_ids) with ordinality as w(entry_id, ordinality);

  return v_draw_id;
end;
$$;

revoke execute on function public.record_draw(uuid, uuid, text, int, text, uuid, uuid[]) from public;
grant  execute on function public.record_draw(uuid, uuid, text, int, text, uuid, uuid[]) to service_role;
