-- SuntCastigator — schema v3: close cross-tenant campaign_products gap
-- Apply via Supabase Dashboard SQL Editor (same as 0001_init.sql / 0002_draw.sql).
-- Do NOT edit this file after it has been applied to any environment —
-- add 0004_*.sql instead.

-- ============================================================================
-- Fix: campaign_products_insert previously only checked that the campaign
-- belonged to the caller's brand, never that the product did too. That let
-- any brand link ANOTHER brand's product into their own campaign (confirmed
-- via a live cross-tenant test during the T6.1 security review). This
-- replaces the policy so the product's brand must match the campaign's
-- brand as well.
-- ============================================================================

drop policy campaign_products_insert on campaign_products;

create policy campaign_products_insert on campaign_products
  for insert to authenticated
  with check (
    exists (
      select 1
      from campaigns c
      join products p on p.id = product_id
      where c.id = campaign_id
        and p.brand_id = c.brand_id
        and is_brand_member(c.brand_id)
    )
  );
