-- SuntCastigator — schema v4: fix rate-limit fail-open
-- Apply via Supabase Dashboard SQL Editor (same as 0001_init.sql / 0002_draw.sql
-- / 0003_campaign_products_brand_check.sql), or `supabase db push`.
-- Do NOT edit this file after it has been applied to any environment —
-- add 0005_*.sql instead.

-- ============================================================================
-- Fix: submit_entry()'s per-IP rate limit silently disabled itself if the
-- `settings` row for 'entry_rate_limit_per_ip_hour' was ever missing.
--
--   select coalesce((value->>'limit')::int, 20)
--     into v_ip_limit
--     from settings
--     where key = 'entry_rate_limit_per_ip_hour';
--
-- The coalesce lived INSIDE the row the query would return. With zero
-- matching rows, `select ... into` leaves v_ip_limit as NULL — the coalesce
-- never runs — and the guard `v_ip_limit is not null` then skips the whole
-- rate-limit block, allowing unlimited entries per IP rather than falling
-- back to the documented default of 20/hour.
--
-- (Confirmed on 2026-08-09 that the current settings row IS present with
-- limit=20 on the checked environment — this was a latent bug, not an
-- active incident there. Still worth closing so a deleted/missing row on
-- any environment can't silently turn rate limiting off.)
--
-- Fix: move the coalesce OUTSIDE a scalar subquery, so it always evaluates
-- — falling back to 20 whether the row is missing entirely or present with
-- a null/malformed value. Everything else in the function is unchanged
-- from 0001_init.sql.
-- ============================================================================

create or replace function public.submit_entry(
  p_campaign_id     uuid,
  p_code            text,
  p_full_name       text,
  p_contact         text,
  p_ip              inet,
  p_gdpr_consent_at timestamptz
)
returns table (entry_id uuid, entry_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign      campaigns%rowtype;
  v_ip_limit      int;
  v_ip_count      int;
  v_contact_count int;
  v_duplicate     boolean;
  v_new_id        uuid;
begin
  if p_code is null or p_full_name is null or p_contact is null or p_gdpr_consent_at is null then
    raise exception 'missing_field' using errcode = '22004';
  end if;

  select * into v_campaign from campaigns where id = p_campaign_id;
  if not found then
    raise exception 'campaign_not_found' using errcode = 'P0002';
  end if;

  if v_campaign.status <> 'active' then
    raise exception 'campaign_not_active' using errcode = 'P0001';
  end if;
  if v_campaign.starts_at is not null and current_date < v_campaign.starts_at then
    raise exception 'campaign_not_started' using errcode = 'P0001';
  end if;
  if v_campaign.ends_at is not null and current_date > v_campaign.ends_at then
    raise exception 'campaign_ended' using errcode = 'P0001';
  end if;

  select coalesce(
    (select (value->>'limit')::int from settings where key = 'entry_rate_limit_per_ip_hour'),
    20
  ) into v_ip_limit;

  if p_ip is not null and v_ip_limit is not null and v_ip_limit > 0 then
    select count(*) into v_ip_count
      from code_entries
      where campaign_id = p_campaign_id
        and ip          = p_ip
        and created_at  > now() - interval '1 hour';
    if v_ip_count >= v_ip_limit then
      raise exception 'rate_limit_ip' using errcode = 'P0001';
    end if;
  end if;

  if v_campaign.limit_per_contact_24h is not null and v_campaign.limit_per_contact_24h > 0 then
    select count(*) into v_contact_count
      from code_entries
      where campaign_id = p_campaign_id
        and contact     = p_contact
        and created_at  > now() - interval '24 hours';
    if v_contact_count >= v_campaign.limit_per_contact_24h then
      raise exception 'rate_limit_contact' using errcode = 'P0001';
    end if;
  end if;

  if v_campaign.code_regex is not null
     and v_campaign.code_regex <> ''
     and p_code !~ v_campaign.code_regex
  then
    if v_campaign.block_invalid_format then
      insert into code_entries(campaign_id, code, full_name, contact, ip, status, gdpr_consent_at)
      values (p_campaign_id, p_code, p_full_name, p_contact, p_ip, 'invalid', p_gdpr_consent_at)
      returning id into v_new_id;
      return query select v_new_id, 'invalid'::text;
      return;
    end if;
  end if;

  if v_campaign.single_use_codes then
    select exists (
      select 1 from code_entries
      where campaign_id = p_campaign_id
        and code        = p_code
        and status      = 'valid'
    ) into v_duplicate;
    if v_duplicate then
      insert into code_entries(campaign_id, code, full_name, contact, ip, status, gdpr_consent_at)
      values (p_campaign_id, p_code, p_full_name, p_contact, p_ip, 'duplicate', p_gdpr_consent_at)
      returning id into v_new_id;
      return query select v_new_id, 'duplicate'::text;
      return;
    end if;
  end if;

  insert into code_entries(campaign_id, code, full_name, contact, ip, status, gdpr_consent_at)
  values (p_campaign_id, p_code, p_full_name, p_contact, p_ip, 'valid', p_gdpr_consent_at)
  returning id into v_new_id;
  return query select v_new_id, 'valid'::text;
end;
$$;

revoke execute on function public.submit_entry(uuid, text, text, text, inet, timestamptz) from public;
grant  execute on function public.submit_entry(uuid, text, text, text, inet, timestamptz) to service_role;
